Reclassify images in s1e3 for sctricter criteria
HarpreetBains94/no_homers_club pull request #13
Opened 2020-05-30 21:11 UTC by Fox-Islam

2020-05-30 21:13 UTC, Fox-Islam commented
Unsure about these changes, reclassification was kind of difficult, a lot of things didn't meet the 'all three facial features' criteria but were probably clearer images of homer than a couple which did have all three, but were somewhat distant

2020-05-30 21:55 UTC, HarpreetBains94 requested changes
After looking through the images I feel like its cool reduce the requirements to three of the following:
 - Zig zag side hair
 - Looped top hair
 - Stubble mouth
 - White shirt
 - Blue pants

Also I feel like we should be removing images caught between two animation frames and let the frame buffer deal with those later.

Images to remove:
 - 496
 - 497
 - 498
 - 503
 - 528
 - 587
 - 963-977
 - 1314

2020-06-01 21:24 UTC, Fox-Islam commented
Removed those images - pushed changes. I'll update the wiki with the new criteria

2020-06-02 16:27 UTC, HarpreetBains94 approved these changes

2020-06-02 16:27 UTC, merged